definitions:
  model.Role:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      role:
        type: string
      updatedAt:
        type: string
      userID:
        type: integer
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
      qq:
        type: integer
      roles:
        items:
          $ref: '#/definitions/model.Role'
        type: array
      updatedAt:
        type: string
    type: object
  request.RegisterRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  response.DebugInfo:
    properties:
      goVersion:
        type: string
      qq:
        properties:
          account:
            type: integer
          online:
            type: boolean
        type: object
      version:
        type: string
    type: object
  response.FailureResponse:
    properties:
      error:
        type: string
      error_message:
        type: string
      ok:
        type: boolean
    type: object
  response.RegisterSuccessResponse:
    properties:
      ok:
        type: boolean
      success_message:
        type: string
      user:
        $ref: '#/definitions/model.User'
    type: object
info:
  contact: {}
  description: Maid Nana 的 Web API
  title: Main Nana API 文档
  version: 1.0.0-alpha
paths:
  /api/about:
    get:
      description: 获取 Maid Nana 调试信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.DebugInfo'
      summary: 调试信息
      tags:
      - about
  /api/user:
    post:
      consumes:
      - application/json
      description: 注册账号
      parameters:
      - description: 注册信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.FailureResponse'
      summary: 注册
      tags:
      - account user register
swagger: "2.0"
